### ISSUE TITLE
Css Property regular expression is missing { 

### ISSUE THREAD

**Issue by ezraroi** [callumlocke/grunt-cdnify#9]
If the css property is the first one in the block, e.g:
```css
.test {background-image:url(_____)}
```

The regular expression will miss it as it is expecting ';' or white space at the beginning.

I fixed it by adding `{`

```js
var cssPropertyMatcher = /[;\s{]*?[a-zA-Z-]+\s*:\s*url(\s*['"]?[^'")\s]+['"]?\s*)[^;}]*/g;
```
